In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score    
from sklearn.manifold import TSNE
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import joblib

In [2]:
new_grid_df = pd.read_csv('new-grid-incidents.csv')

<ipython-input-2-d48818a0547c>:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  new_grid_df = pd.read_csv('new-grid-incidents.csv')

In [3]:
new_grid_df.head()

,unique_incident_id,incident_id,incident_date,incident_day,incident_month,incident_year,summary,is_assassination,is_ied,is_multi_day,...,latitude,longitude,claimed,num_killed,num_killed_perp,num_killed_us,num_wounded,num_wounded_us,num_hostkid,num_hostkid_us
0,180404900,1804049,7/8/18,8,7,2018,"On July 8, 2018, on Buraydah-Tarfiyah Road, Al...",0,0,0,...,26.359231,43.981812,0,4,0,0,1,0,0,0
1,180411700,1804117,7/11/18,11,7,2018,"On July 11, 2018, in Arish, North Sinai, EGYPT...",0,0,0,...,31.132093,33.803276,0,11,0,0,0,0,0,0
2,180641700,1806417,11/4/18,4,11,2018,"On November 4, 2018, in Minya Governorate, EGY...",0,0,0,...,28.087097,30.761840,0,19,0,0,0,0,0,0
3,180339200,1803392,6/4/18,4,6,2018,"On June 4, 2018, in Kabul, AFGHANISTAN, a suic...",0,1,0,...,34.555349,69.207486,1,7,0,0,9,0,0,0
4,180348900,1803489,6/8/18,8,6,2018,"On June 8, 2018, in Jalalabad, Nangarhar Provi...",0,0,0,...,34.428353,70.457802,1,3,0,0,5,0,0,0

In [4]:
new_grid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61736 entries, 0 to 61735
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_incident_id      61736 non-null  object
 1   incident_id             61736 non-null  int64
 2   incident_date           61736 non-null  object
 3   incident_day            61736 non-null  int64
 4   incident_month          61736 non-null  int64
 5   incident_year           61736 non-null  int64
 6   summary                 61736 non-null  object
 7   is_assassination        61736 non-null  int64
 8   is_ied                  61736 non-null  int64
 9   is_multi_day            61736 non-null  int64
 10  is_multi_location       61736 non-null  int64
 11  is_suicide              61736 non-null  int64
 12  country_genc            61736 non-null  object
 13  country_genc_txt        61736 non-null  object
 14  country_nongenc_txt     61736 non-null  object
 15  stateprovince_genc      61736 non-null  object
 16  stateprovince_genc_txt  60094 non-null  object
 17  stateprovince_nongenc   13492 non-null  object
 18  city                    56310 non-null  object
 19  region                  61736 non-null  int64
 20  region_txt              61736 non-null  object
 21  latitude                61237 non-null  float64
 22  longitude               61237 non-null  float64
 23  claimed                 61736 non-null  int64
 24  num_killed              61736 non-null  int64
 25  num_killed_perp         61736 non-null  int64
 26  num_killed_us           61736 non-null  int64
 27  num_wounded             61736 non-null  int64
 28  num_wounded_us          61736 non-null  int64
 29  num_hostkid             61736 non-null  int64
 30  num_hostkid_us          61736 non-null  int64
dtypes: float64(2), int64(18), object(11)
memory usage: 14.6+ MB

In [5]:
# Value counts for 'region' column
region_counts = new_grid_df['region'].value_counts()
print(region_counts)

region
145    20351
202    18447
34     14556
35      3798
419     2479
15      1534
151      136
21       124
155      123
39        83
154       73
53        14
143       12
30         6
Name: count, dtype: int64

In [6]:
# Value counts for 'region_txt' column
region_txt_counts = new_grid_df['region_txt'].value_counts()
print(region_txt_counts)

region_txt
Western Asia                       20351
Sub-Saharan Africa                 18447
Southern Asia                      14556
South-eastern Asia                  3798
Latin America and the Caribbean     2479
Northern Africa                     1534
Eastern Europe                       136
Northern America                     124
Western Europe                       123
Southern Europe                       83
Northern Europe                       73
Australia and New Zealand             14
Central Asia                          12
Eastern Asia                           6
Name: count, dtype: int64

In [7]:
new_grid_df.describe()

,incident_id,incident_day,incident_month,incident_year,is_assassination,is_ied,is_multi_day,is_multi_location,is_suicide,region,latitude,longitude,claimed,num_killed,num_killed_perp,num_killed_us,num_wounded,num_wounded_us,num_hostkid,num_hostkid_us
count,6.173600e+04,61736.000000,61736.000000,61736.000000,61736.000000,61736.000000,61736.000000,61736.000000,61736.000000,61736.000000,61237.000000,61237.000000,61736.000000,61736.000000,61736.000000,61736.000000,61736.000000,61736.000000,61736.000000,61736.000000
mean,1.230015e+06,15.416175,6.002349,2021.119849,0.012586,0.135772,0.031457,0.093754,0.015113,136.485292,21.521593,40.232990,0.152942,2.952637,0.540317,0.003564,1.983608,0.007305,0.518579,0.000405
std,8.588919e+05,8.766354,3.449342,2.125504,0.111479,0.342549,0.174549,0.291489,0.122002,89.621553,14.177054,37.759100,0.359934,8.151473,3.093436,0.168520,8.418026,0.431934,4.910774,0.034853
min,2.200000e+05,1.000000,1.000000,2018.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.000000,-43.532030,-127.647621,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.406608e+05,8.000000,3.000000,2019.000000,0.000000,0.000000,0.000000,0.000000,0.000000,34.000000,10.407299,29.045993,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.804240e+06,15.000000,6.000000,2021.000000,0.000000,0.000000,0.000000,0.000000,0.000000,145.000000,26.029591,40.078687,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2.018496e+06,23.000000,9.000000,2023.000000,0.000000,0.000000,0.000000,0.000000,0.000000,202.000000,33.999938,66.019589,0.000000,3.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000
max,2.114855e+06,31.000000,12.000000,2025.000000,1.000000,1.000000,1.000000,1.000000,1.000000,419.000000,68.973311,174.677501,1.000000,386.000000,150.000000,16.000000,600.000000,64.000000,354.000000,4.000000

In [14]:
X = new_grid_df[['region_txt']]
y = new_grid_df['is_assassination']

In [15]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
preprocessor = ColumnTransformer(
    transformers=[
        ('ohe', OneHotEncoder(handle_unknown='ignore'), ['region_txt'])
    ],
    remainder='drop'
)

# Create a pipeline with preprocessing and a classifier
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

In [17]:
# Fit the pipeline on the training data
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['region_txt'])])),
                ('classifier', LogisticRegression())])

In [18]:
# Make predictions on the test set
y_pred = pipeline.predict(X_test)
# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9869614512471655

In [20]:
# Save the model with joblib
joblib.dump(pipeline, 'log_reg__all_regions_model.pkl')

['log_reg__all_regions_model.pkl']